// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mafwmsxyebgjyorncypj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZndtc3h5ZWJnanlvcm5jeXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDUyMjQsImV4cCI6MjA2Mzg4MTIyNH0.W8Ke54L2qwPYToHGWm4mK3eeQkwgI_-RoszxFVAxubM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);